version: "3.3"
services:
  dev-image_x86:
    image: a2ps/skimage:x86_dev
    privileged: true
    ports:
      - "3000:3000"
    container_name: devenv_x86

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /home/odroid/skimage_edge:/home
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    working_dir: /home/cpp_functions
    
    environment:
    - TZ=Europe/Paris
    - DISPLAY=$DISPLAY
    - SSH_AUTH_SOCK=/tmp/ssh_auth_sock


  dev-image_ARM:
    image: a2ps/skimage:ARM_dev
    privileged: true
    # ports:
    #   - "2000:2000"
    container_name: devenv_ARM

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /home/odroid/skimage_edge_production/:/home/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    working_dir: /home/
    
    environment:
    - TZ=Europe/Paris
    - DISPLAY=$DISPLAY
    - SSH_AUTH_SOCK=/tmp/ssh_auth_sock  
    # network_mode: "host"

  prod_ARM:
    image: a2ps/skimage:ARM_production
    privileged: true
    container_name: prod_ARM

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /home/odroid/skimage_edge_production/:/home/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    working_dir: /home/
    
    environment:
    - TZ=Europe/Paris
    - DISPLAY=$DISPLAY
    - SSH_AUTH_SOCK=/tmp/ssh_auth_sock  
