version: "3.3"
services:
  Skimage:
    image: ${docker_image_name}
    privileged: true
    container_name: skimage

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /home/odroid/skimage_edge_deployment:/home
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    working_dir: /home
    
    environment:
    - TZ=Europe/Paris
    - XAUTHORITY=/tmp/.docker.xauth 
    - DISPLAY=$DISPLAY
    # - SSH_AUTH_SOCK=/tmp/ssh_auth_sock

    entrypoint:
      - python
      - python_src/skimage_edge.py  

    network_mode: "host"

  Watchdog:
    image: ${docker_image_name}
    privileged: true
    container_name: watchdog

    volumes:
      - /home/odroid/skimage_edge_deployment:/home
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    working_dir: /home
    
    environment:
    - TZ=Europe/Paris

    entrypoint:
      - python
      - python_src/watchdog.py

    network_mode: "host"

  Deploy:
    image: "${DOCKER_IMAGE}"
    privileged: true
    container_name: deploy

    volumes:
      - ${ROOT_DIR}/${SOURCE_DIR}:/home
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    working_dir: /home
    
    env_file:
      - skimage_variables.env

    environment:
      - USER_ALL=${USER_ALL}
      - PASSWORD_ALL=${PASSWORD_ALL}

    entrypoint:
      - python
      - Utilities/deployment.py
      - ${OPTION}

    network_mode: "host"

    