version: "3.3"
services:
  Skimage:
    image: "${DOCKER_IMAGE}"
    privileged: true
    container_name: skimage

    volumes:
      - ${ROOT_DIR}/${SOURCE_DIR}:/home
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /bin/dash:/bin/sh # required for system commands on the odroid

    working_dir: /home

    env_file:
      - skimage_variables.env

    environment:
      - XAUTHORITY=/tmp/.docker.xauth 
      - DISPLAY=$DISPLAY

    entrypoint:
      - python
      - python_src/skimage_edge.py  

    network_mode: "host"

  Watchdog:
    image: "${DOCKER_IMAGE}"
    privileged: true
    container_name: watchdog

    volumes:
      - ${ROOT_DIR}/${SOURCE_DIR}:/home
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    working_dir: /home
    
    env_file:
      - skimage_variables.env

    entrypoint:
      - python
      - python_src/watchdog.py

    network_mode: "host"

  Deploy:
    image: "${DOCKER_IMAGE}"
    privileged: true
    container_name: deploy

    volumes:
      - ${ROOT_DIR}/${SOURCE_DIR}:/home
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    working_dir: /home
    
    env_file:
      - skimage_variables.env

    environment:
      - USER_ALL=${USER_ALL}
      - PASSWORD_ALL=${PASSWORD_ALL}

    entrypoint:
      - python
      - Utilities/deployment.py
      - ${OPTION}

    network_mode: "host"

  Bash:
    image: "${DOCKER_IMAGE}"
    privileged: true
    container_name: bash

    volumes:
      - ${ROOT_DIR}/${SOURCE_DIR}:/home
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /bin/dash:/bin/sh # required for system commands on the odroid

    working_dir: /home

    env_file:
      - skimage_variables.env

    environment:
      - XAUTHORITY=/tmp/.docker.xauth 
      - DISPLAY=$DISPLAY

    entrypoint:
      - bash

    network_mode: "host"